config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/tasks", to: "tasks#index"

  get "/tasks/new", to: "tasks#new", as: :new
  post "/tasks", to: "tasks#create"

  get "/tasks/:id", to: "tasks#show", as: :task

  get "/tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "/tasks/:id", to: "tasks#update"

  delete "/tasks/:id", to: "tasks#destroy", as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id].to_i)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(strong_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id].to_i)
  end

  def update
    @task = Task.find(params[:id].to_i)
    @task.update(strong_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id].to_i)
    @task.destroy
    redirect_to tasks_path
  end

  private

  def strong_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css" %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag src="https://kit.fontawesome.com/bcde4951cc.js" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">

<%= link_to tasks_path do %>
<i class="fas fa-arrow-left"></i>
<% end %>

<%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.label :completed %>
<%= f.check_box :completed %>
<%= f.submit %>
<% end %>

</div>

app/views/tasks/index.html.erb
<div class="container">

  <h1>Tasks</h1>

  <% @tasks.each do |t| %>
    <div class="d-flex align-items-center">
      <%= link_to edit_path(t) do %>
        <% if t.completed%>
          <i class="fas fa-check-square"></i>
        <% else %>
          <i class="fas fa-square"></i>
        <% end %>
      <% end %>

      <h3 class="title"><%= link_to t.title, task_path(t) %></h3>

      <%= link_to destroy_path(t), method: :delete, data: { confirm: 'are you sure?'} do %>
      <i class="fas fa-trash"></i>
      <% end %>
  </div>
  <% end %>

<%= link_to new_path do %>
<p><i class="fas fa-plus"></i> New Task</p>
<% end %>

</div>

app/views/tasks/new.html.erb
<div class="container">

<%= link_to tasks_path do %>
<i class="fas fa-arrow-left"></i>
<% end %>

<%= form_for(@task) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :details %>
<%= f.text_field :details %>
<%= f.submit %>
<% end %>

</div>

app/views/tasks/show.html.erb
<div class="container">

<%= link_to tasks_path do %>
<i class="fas fa-arrow-left"></i>
<% end %>

<h3><%= @task.title %></h3>

<%= link_to edit_path(@task) do %>
  <% if @task.completed %>
    <p><i class="fas fa-check-square"></i> Completed</p>
  <% else %>
    <p><i class="fas fa-square"></i> Incomplete</i></p>
  <% end %>
<% end %>

<p><%= @task.details %></p>

<%= link_to edit_path(@task) do %>
<p><i class="fas fa-edit"></i> Edit</p>
<% end %>

</div>